### ISSUE TITLE
Zoom resets when arrow key is pressed

### ISSUE THREAD

**Issue by ntoles** [PrincetonUniversity/Iseult#15]

**Comment by bcaddy** [comment]
It looks like it resets when you use the left or right arrows to switch datasets, the up/down arrows don't do anything. Is that what you found?

**Comment by bcaddy** [comment]
I figured out the issue. I missed adding some parameters to a loop. That uncovered some other issues with the matplotlib API issues I found earlier. I'll let you know when they're all fixed

**Comment by ntoles** [comment]
Yes, only right and left arrows work (or use mouse to click > and < buttons
next to Play, it's the same thing)

**Comment by bcaddy** [comment]
For when/if I come back to this. The issue is that the protected `view` variable from matplotlib's `_nav_stack().items` (accessed like this ` ax, (view, (pos_orig, pos_active)) = self.toolbar._nav_stack().items()`) changed format somewhere between matplotlib v3.7.2 and v3.8.4. It went from a list like `[x_low_lim, x_high_lim, y_low_lim, y_high_lim]` to a dictionary with keys `xlim` and `ylim`, in addition to a few others. Fixing this is not trivial and kept leading to more and more bugs so I stopped. 

As a workaround, stick to matplotlib v3.7.x.

Note that Iseult v2 doesn't use this method and so shouldn't be effected by this change in matplotlib.
